### ISSUE TITLE
Nullspace, sign change

### ISSUE THREAD

**Issue by shivashankarrs** [shauli-ravfogel/nullspace_projection#2]
Thanks for the work and code repo. I have a query here (maybe a minor one), what is the effect of changing sign based on first basis value (w_basis = w_basis * np.sign(w_basis[0][0])).

**Comment by shauli-ravfogel** [comment]
Hi, and sorry for the late response. 

Scipy's `orth` uses SVD, and there is an inherent sign ambiguity associated with SVD, see [here](https://prod-ng.sandia.gov/techlib-noauth/access-control.cgi/2007/076422.pdf). However, since the rowspace is is the same regardless of the sign of its basis vectors, we can safely remove this line from the code.

**Comment by shivashankarrs** [comment]
Thanks for the reference :)
